INSERT INTO interviews (session_id, issue_text, severity_score, primary_category, location_bucket, evidence_span, raw_log) VALUES
('d8425492', '가로등이 없어서 밤길이 위험합니다 항상 불편해요.', 4, '안전 (Safety)', '서면 2번가 인근', '가로등이 없어서 밤길이 위험...', '{"generated_by": "seed script"}'::jsonb),
('1c209da1', '취객이 많아서 밤에 다니기 두려워요.', 4, '안전 (Safety)', '서면 2번가 인근', '취객이 많아서 밤에 다니기 ...', '{"generated_by": "seed script"}'::jsonb),
('597a0dd7', '골목이 너무 어두워서 무서워요.', 4, '안전 (Safety)', '서면 2번가 인근', '골목이 너무 어두워서 무서워...', '{"generated_by": "seed script"}'::jsonb),
('c53cb1da', '골목이 너무 어두워서 무서워요 진짜 불편해요.', 4, '안전 (Safety)', '서면 2번가 인근', '골목이 너무 어두워서 무서워...', '{"generated_by": "seed script"}'::jsonb),
('3f212b25', '골목이 너무 어두워서 무서워요 정말 불편해요.', 4, '안전 (Safety)', '서면 2번가 인근', '골목이 너무 어두워서 무서워...', '{"generated_by": "seed script"}'::jsonb),
('eabee939', 'CCTV가 부족해서 범죄 사각지대 같아요.', 4, '안전 (Safety)', '서면 2번가 인근', 'CCTV가 부족해서 범죄 사...', '{"generated_by": "seed script"}'::jsonb),
('2fe71e49', 'CCTV가 부족해서 범죄 사각지대 같아요 매번 불편해요.', 4, '안전 (Safety)', '서면 2번가 인근', 'CCTV가 부족해서 범죄 사...', '{"generated_by": "seed script"}'::jsonb),
('b59e749f', '가로등이 없어서 밤길이 위험합니다.', 4, '안전 (Safety)', '서면 2번가 인근', '가로등이 없어서 밤길이 위험...', '{"generated_by": "seed script"}'::jsonb),
('8a5a09b6', '가로등이 없어서 밤길이 위험합니다 매번 불편해요.', 4, '안전 (Safety)', '서면 2번가 인근', '가로등이 없어서 밤길이 위험...', '{"generated_by": "seed script"}'::jsonb),
('48f20959', '조명이 너무 어둡습니다 너무 불편해요. 밝게 해주세요 너무 불편해요.', 4, '안전 (Safety)', '서면 2번가 인근', '조명이 너무 어둡습니다 너무...', '{"generated_by": "seed script"}'::jsonb),
('c176772e', '가로등이 없어서 밤길이 위험합니다 정말 불편해요.', 4, '안전 (Safety)', '서면 2번가 인근', '가로등이 없어서 밤길이 위험...', '{"generated_by": "seed script"}'::jsonb),
('abdb5856', '가로등이 없어서 밤길이 위험합니다 너무 불편해요.', 4, '안전 (Safety)', '서면 2번가 인근', '가로등이 없어서 밤길이 위험...', '{"generated_by": "seed script"}'::jsonb),
('4520b681', 'CCTV가 부족해서 범죄 사각지대 같아요 매번 불편해요.', 4, '안전 (Safety)', '서면 2번가 인근', 'CCTV가 부족해서 범죄 사...', '{"generated_by": "seed script"}'::jsonb),
('2abff4b5', 'CCTV가 부족해서 범죄 사각지대 같아요.', 4, '안전 (Safety)', '서면 2번가 인근', 'CCTV가 부족해서 범죄 사...', '{"generated_by": "seed script"}'::jsonb),
('30d96a8b', '취객이 많아서 밤에 다니기 두려워요 항상 불편해요.', 4, '안전 (Safety)', '서면 2번가 인근', '취객이 많아서 밤에 다니기 ...', '{"generated_by": "seed script"}'::jsonb),
('0817f4e3', '골목이 너무 어두워서 무서워요 정말 불편해요.', 4, '안전 (Safety)', '서면 2번가 인근', '골목이 너무 어두워서 무서워...', '{"generated_by": "seed script"}'::jsonb),
('f51e4a2a', '엘리베이터가 고장나서 이동할 수가 없어요 너무 불편해요.', 3, '접근성 (Accessibility)', '해운대 (Haeundae)', '엘리베이터가 고장나서 이동할...', '{"generated_by": "seed script"}'::jsonb),
('10894552', '휠체어가 다닐 수 있는 경사로가 없습니다.', 3, '접근성 (Accessibility)', '해운대 (Haeundae)', '휠체어가 다닐 수 있는 경사...', '{"generated_by": "seed script"}'::jsonb),
('76dead4d', '휠체어가 다닐 수 있는 경사로가 없습니다 항상 불편해요.', 3, '접근성 (Accessibility)', '해운대 (Haeundae)', '휠체어가 다닐 수 있는 경사...', '{"generated_by": "seed script"}'::jsonb),
('f956097a', '보도블럭 턱이 너무 높아서 휠체어 이동이 힘들어요.', 3, '접근성 (Accessibility)', '해운대 (Haeundae)', '보도블럭 턱이 너무 높아서 ...', '{"generated_by": "seed script"}'::jsonb),
('c7d8be23', '휠체어가 다닐 수 있는 경사로가 없습니다 정말 불편해요.', 3, '접근성 (Accessibility)', '해운대 (Haeundae)', '휠체어가 다닐 수 있는 경사...', '{"generated_by": "seed script"}'::jsonb),
('c877bccf', '엘리베이터가 고장나서 이동할 수가 없어요 매번 불편해요.', 3, '접근성 (Accessibility)', '해운대 (Haeundae)', '엘리베이터가 고장나서 이동할...', '{"generated_by": "seed script"}'::jsonb),
('e4580085', '휠체어가 다닐 수 있는 경사로가 없습니다.', 3, '접근성 (Accessibility)', '해운대 (Haeundae)', '휠체어가 다닐 수 있는 경사...', '{"generated_by": "seed script"}'::jsonb),
('138670a3', '보도블럭 턱이 너무 높아서 휠체어 이동이 힘들어요 정말 불편해요.', 3, '접근성 (Accessibility)', '해운대 (Haeundae)', '보도블럭 턱이 너무 높아서 ...', '{"generated_by": "seed script"}'::jsonb),
('7f9f07c6', '계단밖에 없어서 유모차나 휠체어는 못 지나갑니다.', 3, '접근성 (Accessibility)', '해운대 (Haeundae)', '계단밖에 없어서 유모차나 휠...', '{"generated_by": "seed script"}'::jsonb),
('594cc58a', '장애인 편의시설이 전무합니다 정말 불편해요.', 3, '접근성 (Accessibility)', '해운대 (Haeundae)', '장애인 편의시설이 전무합니다...', '{"generated_by": "seed script"}'::jsonb),
('cc59460e', '장애인 편의시설이 전무합니다 진짜 불편해요.', 3, '접근성 (Accessibility)', '해운대 (Haeundae)', '장애인 편의시설이 전무합니다...', '{"generated_by": "seed script"}'::jsonb),
('e4584a17', '계단밖에 없어서 유모차나 휠체어는 못 지나갑니다 정말 불편해요.', 3, '접근성 (Accessibility)', '해운대 (Haeundae)', '계단밖에 없어서 유모차나 휠...', '{"generated_by": "seed script"}'::jsonb),
('7441478e', '휠체어가 다닐 수 있는 경사로가 없습니다.', 3, '접근성 (Accessibility)', '해운대 (Haeundae)', '휠체어가 다닐 수 있는 경사...', '{"generated_by": "seed script"}'::jsonb),
('7c7a9ea4', '엘리베이터가 고장나서 이동할 수가 없어요.', 3, '접근성 (Accessibility)', '해운대 (Haeundae)', '엘리베이터가 고장나서 이동할...', '{"generated_by": "seed script"}'::jsonb),
('8229df98', '보도블럭 턱이 너무 높아서 휠체어 이동이 힘들어요 정말 불편해요.', 3, '접근성 (Accessibility)', '해운대 (Haeundae)', '보도블럭 턱이 너무 높아서 ...', '{"generated_by": "seed script"}'::jsonb),
('17c3aa53', '휠체어가 다닐 수 있는 경사로가 없습니다 너무 불편해요.', 3, '접근성 (Accessibility)', '해운대 (Haeundae)', '휠체어가 다닐 수 있는 경사...', '{"generated_by": "seed script"}'::jsonb),
('0fab2574', '보도블럭 턱이 너무 높아서 휠체어 이동이 힘들어요.', 3, '접근성 (Accessibility)', '해운대 (Haeundae)', '보도블럭 턱이 너무 높아서 ...', '{"generated_by": "seed script"}'::jsonb),
('85df086f', '엘리베이터가 고장나서 이동할 수가 없어요.', 3, '접근성 (Accessibility)', '해운대 (Haeundae)', '엘리베이터가 고장나서 이동할...', '{"generated_by": "seed script"}'::jsonb),
('8fe2e233', '휠체어가 다닐 수 있는 경사로가 없습니다 정말 불편해요.', 3, '접근성 (Accessibility)', '해운대 (Haeundae)', '휠체어가 다닐 수 있는 경사...', '{"generated_by": "seed script"}'::jsonb),
('8fb7b60d', '계단밖에 없어서 유모차나 휠체어는 못 지나갑니다 정말 불편해요.', 3, '접근성 (Accessibility)', '해운대 (Haeundae)', '계단밖에 없어서 유모차나 휠...', '{"generated_by": "seed script"}'::jsonb),
('d68c8aaf', '휠체어가 다닐 수 있는 경사로가 없습니다 진짜 불편해요.', 3, '접근성 (Accessibility)', '해운대 (Haeundae)', '휠체어가 다닐 수 있는 경사...', '{"generated_by": "seed script"}'::jsonb),
('a2f2f7a1', '엘리베이터가 고장나서 이동할 수가 없어요 항상 불편해요.', 3, '접근성 (Accessibility)', '해운대 (Haeundae)', '엘리베이터가 고장나서 이동할...', '{"generated_by": "seed script"}'::jsonb),
('f21ec114', '계단밖에 없어서 유모차나 휠체어는 못 지나갑니다 너무 불편해요.', 3, '접근성 (Accessibility)', '해운대 (Haeundae)', '계단밖에 없어서 유모차나 휠...', '{"generated_by": "seed script"}'::jsonb),
('4f92ed4a', '장애인 편의시설이 전무합니다 매번 불편해요.', 3, '접근성 (Accessibility)', '해운대 (Haeundae)', '장애인 편의시설이 전무합니다...', '{"generated_by": "seed script"}'::jsonb),
('bae95e71', '엘리베이터가 고장나서 이동할 수가 없어요.', 3, '접근성 (Accessibility)', '해운대 (Haeundae)', '엘리베이터가 고장나서 이동할...', '{"generated_by": "seed script"}'::jsonb),
('7d91afc6', '장애인 편의시설이 전무합니다 매번 불편해요.', 3, '접근성 (Accessibility)', '해운대 (Haeundae)', '장애인 편의시설이 전무합니다...', '{"generated_by": "seed script"}'::jsonb),
('c766dba8', '엘리베이터가 고장나서 이동할 수가 없어요 정말 불편해요.', 3, '접근성 (Accessibility)', '해운대 (Haeundae)', '엘리베이터가 고장나서 이동할...', '{"generated_by": "seed script"}'::jsonb),
('7c3f2615', '엘리베이터가 고장나서 이동할 수가 없어요.', 3, '접근성 (Accessibility)', '해운대 (Haeundae)', '엘리베이터가 고장나서 이동할...', '{"generated_by": "seed script"}'::jsonb),
('047aa2a5', '엘리베이터가 고장나서 이동할 수가 없어요 진짜 불편해요.', 3, '접근성 (Accessibility)', '해운대 (Haeundae)', '엘리베이터가 고장나서 이동할...', '{"generated_by": "seed script"}'::jsonb),
('11efbc47', '보도블럭 턱이 너무 높아서 휠체어 이동이 힘들어요.', 3, '접근성 (Accessibility)', '해운대 (Haeundae)', '보도블럭 턱이 너무 높아서 ...', '{"generated_by": "seed script"}'::jsonb),
('9a2752b6', '엘리베이터가 고장나서 이동할 수가 없어요 매번 불편해요.', 3, '접근성 (Accessibility)', '해운대 (Haeundae)', '엘리베이터가 고장나서 이동할...', '{"generated_by": "seed script"}'::jsonb),
('d4de2b0d', '휠체어가 다닐 수 있는 경사로가 없습니다.', 3, '접근성 (Accessibility)', '해운대 (Haeundae)', '휠체어가 다닐 수 있는 경사...', '{"generated_by": "seed script"}'::jsonb),
('551339fa', '장애인 편의시설이 전무합니다 항상 불편해요.', 3, '접근성 (Accessibility)', '해운대 (Haeundae)', '장애인 편의시설이 전무합니다...', '{"generated_by": "seed script"}'::jsonb),
('2abf6524', '휠체어가 다닐 수 있는 경사로가 없습니다 매번 불편해요.', 3, '접근성 (Accessibility)', '해운대 (Haeundae)', '휠체어가 다닐 수 있는 경사...', '{"generated_by": "seed script"}'::jsonb),
('5adb4079', '엘리베이터가 고장나서 이동할 수가 없어요 항상 불편해요.', 3, '접근성 (Accessibility)', '해운대 (Haeundae)', '엘리베이터가 고장나서 이동할...', '{"generated_by": "seed script"}'::jsonb),
('8f20debb', '휠체어가 다닐 수 있는 경사로가 없습니다 너무 불편해요.', 3, '접근성 (Accessibility)', '해운대 (Haeundae)', '휠체어가 다닐 수 있는 경사...', '{"generated_by": "seed script"}'::jsonb),
('9c5f5f60', '휠체어가 다닐 수 있는 경사로가 없습니다 매번 불편해요.', 3, '접근성 (Accessibility)', '해운대 (Haeundae)', '휠체어가 다닐 수 있는 경사...', '{"generated_by": "seed script"}'::jsonb),
('a3aa6da1', '엘리베이터가 고장나서 이동할 수가 없어요 진짜 불편해요.', 3, '접근성 (Accessibility)', '해운대 (Haeundae)', '엘리베이터가 고장나서 이동할...', '{"generated_by": "seed script"}'::jsonb),
('1aa4d144', '엘리베이터가 고장나서 이동할 수가 없어요 항상 불편해요.', 3, '접근성 (Accessibility)', '해운대 (Haeundae)', '엘리베이터가 고장나서 이동할...', '{"generated_by": "seed script"}'::jsonb),
('4e6024e5', '엘리베이터가 고장나서 이동할 수가 없어요.', 3, '접근성 (Accessibility)', '해운대 (Haeundae)', '엘리베이터가 고장나서 이동할...', '{"generated_by": "seed script"}'::jsonb),
('370444e0', '장애인 편의시설이 전무합니다.', 3, '접근성 (Accessibility)', '해운대 (Haeundae)', '장애인 편의시설이 전무합니다...', '{"generated_by": "seed script"}'::jsonb),
('c81c23b5', '엘리베이터가 고장나서 이동할 수가 없어요 너무 불편해요.', 3, '접근성 (Accessibility)', '해운대 (Haeundae)', '엘리베이터가 고장나서 이동할...', '{"generated_by": "seed script"}'::jsonb),
('1d98dfb5', '장애인 편의시설이 전무합니다 정말 불편해요.', 3, '접근성 (Accessibility)', '해운대 (Haeundae)', '장애인 편의시설이 전무합니다...', '{"generated_by": "seed script"}'::jsonb),
('800cc6d0', '엘리베이터가 고장나서 이동할 수가 없어요 항상 불편해요.', 3, '접근성 (Accessibility)', '해운대 (Haeundae)', '엘리베이터가 고장나서 이동할...', '{"generated_by": "seed script"}'::jsonb),
('b9ebd76a', '보도블럭 턱이 너무 높아서 휠체어 이동이 힘들어요 진짜 불편해요.', 3, '접근성 (Accessibility)', '해운대 (Haeundae)', '보도블럭 턱이 너무 높아서 ...', '{"generated_by": "seed script"}'::jsonb),
('c98f3f78', '보도블럭 턱이 너무 높아서 휠체어 이동이 힘들어요 정말 불편해요.', 3, '접근성 (Accessibility)', '해운대 (Haeundae)', '보도블럭 턱이 너무 높아서 ...', '{"generated_by": "seed script"}'::jsonb),
('07353407', '보도블럭 턱이 너무 높아서 휠체어 이동이 힘들어요 너무 불편해요.', 3, '접근성 (Accessibility)', '해운대 (Haeundae)', '보도블럭 턱이 너무 높아서 ...', '{"generated_by": "seed script"}'::jsonb),
('5d09fd4c', '장애인 편의시설이 전무합니다.', 3, '접근성 (Accessibility)', '해운대 (Haeundae)', '장애인 편의시설이 전무합니다...', '{"generated_by": "seed script"}'::jsonb),
('8fbf4bcf', '해변가에 쓰레기가 너무 많아요.', 2, '쾌적성 (Comfort)', '광안리 (Gwangalli)', '해변가에 쓰레기가 너무 많아...', '{"generated_by": "seed script"}'::jsonb),
('48515bc5', '폭죽 쓰레기가 여기저기 널려있어서 더러워요.', 2, '쾌적성 (Comfort)', '광안리 (Gwangalli)', '폭죽 쓰레기가 여기저기 널려...', '{"generated_by": "seed script"}'::jsonb),
('afabd2a8', '폭죽 쓰레기가 여기저기 널려있어서 더러워요.', 2, '쾌적성 (Comfort)', '광안리 (Gwangalli)', '폭죽 쓰레기가 여기저기 널려...', '{"generated_by": "seed script"}'::jsonb),
('247bb20e', '해변가에 쓰레기가 너무 많아요.', 2, '쾌적성 (Comfort)', '광안리 (Gwangalli)', '해변가에 쓰레기가 너무 많아...', '{"generated_by": "seed script"}'::jsonb),
('6317e105', '쓰레기통이 넘쳐서 냄새가 심합니다.', 2, '쾌적성 (Comfort)', '광안리 (Gwangalli)', '쓰레기통이 넘쳐서 냄새가 심...', '{"generated_by": "seed script"}'::jsonb),
('a92b0d91', '거리가 너무 지저분하고 악취가 납니다 항상 불편해요.', 2, '쾌적성 (Comfort)', '광안리 (Gwangalli)', '거리가 너무 지저분하고 악취...', '{"generated_by": "seed script"}'::jsonb),
('bcf872db', '거리가 너무 지저분하고 악취가 납니다 정말 불편해요.', 2, '쾌적성 (Comfort)', '광안리 (Gwangalli)', '거리가 너무 지저분하고 악취...', '{"generated_by": "seed script"}'::jsonb),
('99141ef7', '거리가 너무 지저분하고 악취가 납니다 진짜 불편해요.', 2, '쾌적성 (Comfort)', '광안리 (Gwangalli)', '거리가 너무 지저분하고 악취...', '{"generated_by": "seed script"}'::jsonb),
('b88d5c6c', '일회용 컵들이 길거리에 방치되어 있어요 너무 불편해요.', 2, '쾌적성 (Comfort)', '광안리 (Gwangalli)', '일회용 컵들이 길거리에 방치...', '{"generated_by": "seed script"}'::jsonb),
('f615ea95', '거리가 너무 지저분하고 악취가 납니다 항상 불편해요.', 2, '쾌적성 (Comfort)', '광안리 (Gwangalli)', '거리가 너무 지저분하고 악취...', '{"generated_by": "seed script"}'::jsonb),
('b958adaa', '폭죽 쓰레기가 여기저기 널려있어서 더러워요 매번 불편해요.', 2, '쾌적성 (Comfort)', '광안리 (Gwangalli)', '폭죽 쓰레기가 여기저기 널려...', '{"generated_by": "seed script"}'::jsonb),
('27858102', '해변가에 쓰레기가 너무 많아요 매번 불편해요.', 2, '쾌적성 (Comfort)', '광안리 (Gwangalli)', '해변가에 쓰레기가 너무 많아...', '{"generated_by": "seed script"}'::jsonb),
('e90178df', '일회용 컵들이 길거리에 방치되어 있어요 진짜 불편해요.', 2, '쾌적성 (Comfort)', '광안리 (Gwangalli)', '일회용 컵들이 길거리에 방치...', '{"generated_by": "seed script"}'::jsonb),
('390205df', '거리가 너무 지저분하고 악취가 납니다.', 2, '쾌적성 (Comfort)', '광안리 (Gwangalli)', '거리가 너무 지저분하고 악취...', '{"generated_by": "seed script"}'::jsonb),
('17d2741a', '쓰레기통이 넘쳐서 냄새가 심합니다.', 2, '쾌적성 (Comfort)', '광안리 (Gwangalli)', '쓰레기통이 넘쳐서 냄새가 심...', '{"generated_by": "seed script"}'::jsonb),
('fa79d334', '거리가 너무 지저분하고 악취가 납니다 진짜 불편해요.', 2, '쾌적성 (Comfort)', '광안리 (Gwangalli)', '거리가 너무 지저분하고 악취...', '{"generated_by": "seed script"}'::jsonb),
('509f82a8', '일회용 컵들이 길거리에 방치되어 있어요 진짜 불편해요.', 2, '쾌적성 (Comfort)', '광안리 (Gwangalli)', '일회용 컵들이 길거리에 방치...', '{"generated_by": "seed script"}'::jsonb),
('80051030', '해변가에 쓰레기가 너무 많아요 진짜 불편해요.', 2, '쾌적성 (Comfort)', '광안리 (Gwangalli)', '해변가에 쓰레기가 너무 많아...', '{"generated_by": "seed script"}'::jsonb),
('8f1b5a24', '일회용 컵들이 길거리에 방치되어 있어요 항상 불편해요.', 2, '쾌적성 (Comfort)', '광안리 (Gwangalli)', '일회용 컵들이 길거리에 방치...', '{"generated_by": "seed script"}'::jsonb),
('f5a37b24', '폭죽 쓰레기가 여기저기 널려있어서 더러워요 매번 불편해요.', 2, '쾌적성 (Comfort)', '광안리 (Gwangalli)', '폭죽 쓰레기가 여기저기 널려...', '{"generated_by": "seed script"}'::jsonb),
('1eeda602', '폭죽 쓰레기가 여기저기 널려있어서 더러워요 항상 불편해요.', 2, '쾌적성 (Comfort)', '광안리 (Gwangalli)', '폭죽 쓰레기가 여기저기 널려...', '{"generated_by": "seed script"}'::jsonb),
('8ae02d31', '폭죽 쓰레기가 여기저기 널려있어서 더러워요 정말 불편해요.', 2, '쾌적성 (Comfort)', '광안리 (Gwangalli)', '폭죽 쓰레기가 여기저기 널려...', '{"generated_by": "seed script"}'::jsonb),
('d7847b24', '일회용 컵들이 길거리에 방치되어 있어요.', 2, '쾌적성 (Comfort)', '광안리 (Gwangalli)', '일회용 컵들이 길거리에 방치...', '{"generated_by": "seed script"}'::jsonb),
('8bd9022c', '거리가 너무 지저분하고 악취가 납니다 너무 불편해요.', 2, '쾌적성 (Comfort)', '광안리 (Gwangalli)', '거리가 너무 지저분하고 악취...', '{"generated_by": "seed script"}'::jsonb),
('b633dd75', '쓰레기통이 넘쳐서 냄새가 심합니다.', 2, '쾌적성 (Comfort)', '광안리 (Gwangalli)', '쓰레기통이 넘쳐서 냄새가 심...', '{"generated_by": "seed script"}'::jsonb),
('2235482c', '해변가에 쓰레기가 너무 많아요.', 2, '쾌적성 (Comfort)', '광안리 (Gwangalli)', '해변가에 쓰레기가 너무 많아...', '{"generated_by": "seed script"}'::jsonb),
('cc01c250', '해변가에 쓰레기가 너무 많아요 매번 불편해요.', 2, '쾌적성 (Comfort)', '광안리 (Gwangalli)', '해변가에 쓰레기가 너무 많아...', '{"generated_by": "seed script"}'::jsonb),
('dce1552c', '폭죽 쓰레기가 여기저기 널려있어서 더러워요 진짜 불편해요.', 2, '쾌적성 (Comfort)', '광안리 (Gwangalli)', '폭죽 쓰레기가 여기저기 널려...', '{"generated_by": "seed script"}'::jsonb),
('2ed0531e', '거리가 너무 지저분하고 악취가 납니다 너무 불편해요.', 2, '쾌적성 (Comfort)', '광안리 (Gwangalli)', '거리가 너무 지저분하고 악취...', '{"generated_by": "seed script"}'::jsonb),
('bd84dd07', '일회용 컵들이 길거리에 방치되어 있어요 매번 불편해요.', 2, '쾌적성 (Comfort)', '광안리 (Gwangalli)', '일회용 컵들이 길거리에 방치...', '{"generated_by": "seed script"}'::jsonb),
('b8322015', '일회용 컵들이 길거리에 방치되어 있어요.', 2, '쾌적성 (Comfort)', '광안리 (Gwangalli)', '일회용 컵들이 길거리에 방치...', '{"generated_by": "seed script"}'::jsonb),
('3e9bd0a3', '거리가 너무 지저분하고 악취가 납니다 진짜 불편해요.', 2, '쾌적성 (Comfort)', '광안리 (Gwangalli)', '거리가 너무 지저분하고 악취...', '{"generated_by": "seed script"}'::jsonb),
('3c86d559', '일회용 컵들이 길거리에 방치되어 있어요 항상 불편해요.', 2, '쾌적성 (Comfort)', '광안리 (Gwangalli)', '일회용 컵들이 길거리에 방치...', '{"generated_by": "seed script"}'::jsonb),
('3fcfafb4', '해변가에 쓰레기가 너무 많아요.', 2, '쾌적성 (Comfort)', '광안리 (Gwangalli)', '해변가에 쓰레기가 너무 많아...', '{"generated_by": "seed script"}'::jsonb),
('8ac05594', '폭죽 쓰레기가 여기저기 널려있어서 더러워요 정말 불편해요.', 2, '쾌적성 (Comfort)', '광안리 (Gwangalli)', '폭죽 쓰레기가 여기저기 널려...', '{"generated_by": "seed script"}'::jsonb),
('ce5a0382', '쓰레기통이 넘쳐서 냄새가 심합니다.', 2, '쾌적성 (Comfort)', '광안리 (Gwangalli)', '쓰레기통이 넘쳐서 냄새가 심...', '{"generated_by": "seed script"}'::jsonb),
('470182b7', '일회용 컵들이 길거리에 방치되어 있어요 정말 불편해요.', 2, '쾌적성 (Comfort)', '광안리 (Gwangalli)', '일회용 컵들이 길거리에 방치...', '{"generated_by": "seed script"}'::jsonb),
('0accea63', '해변가에 쓰레기가 너무 많아요.', 2, '쾌적성 (Comfort)', '광안리 (Gwangalli)', '해변가에 쓰레기가 너무 많아...', '{"generated_by": "seed script"}'::jsonb),
('5f1ff3ad', '쓰레기통이 넘쳐서 냄새가 심합니다 매번 불편해요.', 2, '쾌적성 (Comfort)', '광안리 (Gwangalli)', '쓰레기통이 넘쳐서 냄새가 심...', '{"generated_by": "seed script"}'::jsonb),
('b2a8b728', '폭죽 쓰레기가 여기저기 널려있어서 더러워요 항상 불편해요.', 2, '쾌적성 (Comfort)', '광안리 (Gwangalli)', '폭죽 쓰레기가 여기저기 널려...', '{"generated_by": "seed script"}'::jsonb),
('77a650b0', '폭죽 쓰레기가 여기저기 널려있어서 더러워요 진짜 불편해요.', 2, '쾌적성 (Comfort)', '광안리 (Gwangalli)', '폭죽 쓰레기가 여기저기 널려...', '{"generated_by": "seed script"}'::jsonb),
('2c67aa28', '폭죽 쓰레기가 여기저기 널려있어서 더러워요 매번 불편해요.', 2, '쾌적성 (Comfort)', '광안리 (Gwangalli)', '폭죽 쓰레기가 여기저기 널려...', '{"generated_by": "seed script"}'::jsonb),
('6152ef7e', '해변가에 쓰레기가 너무 많아요 진짜 불편해요.', 2, '쾌적성 (Comfort)', '광안리 (Gwangalli)', '해변가에 쓰레기가 너무 많아...', '{"generated_by": "seed script"}'::jsonb),
('dce05945', '해변가에 쓰레기가 너무 많아요 너무 불편해요.', 2, '쾌적성 (Comfort)', '광안리 (Gwangalli)', '해변가에 쓰레기가 너무 많아...', '{"generated_by": "seed script"}'::jsonb),
('d90effa9', '해변가에 쓰레기가 너무 많아요.', 2, '쾌적성 (Comfort)', '광안리 (Gwangalli)', '해변가에 쓰레기가 너무 많아...', '{"generated_by": "seed script"}'::jsonb),
('a7faa1f4', '해변가에 쓰레기가 너무 많아요 너무 불편해요.', 2, '쾌적성 (Comfort)', '광안리 (Gwangalli)', '해변가에 쓰레기가 너무 많아...', '{"generated_by": "seed script"}'::jsonb),
('12ef7072', '거리가 너무 지저분하고 악취가 납니다 항상 불편해요.', 2, '쾌적성 (Comfort)', '광안리 (Gwangalli)', '거리가 너무 지저분하고 악취...', '{"generated_by": "seed script"}'::jsonb),
('98520e2e', '지도가 잘못되어 있어서 엉뚱한 곳으로 갔습니다.', 1, '길찾기 (Wayfinding)', '센텀시티 (Centum City)', '지도가 잘못되어 있어서 엉뚱...', '{"generated_by": "seed script"}'::jsonb),
('a9ea9076', '지하철 출구가 너무 복잡해서 길을 잃었어요 너무 불편해요.', 1, '길찾기 (Wayfinding)', '센텀시티 (Centum City)', '지하철 출구가 너무 복잡해서...', '{"generated_by": "seed script"}'::jsonb),
('2b461a28', '지하철 출구가 너무 복잡해서 길을 잃었어요 너무 불편해요.', 1, '길찾기 (Wayfinding)', '센텀시티 (Centum City)', '지하철 출구가 너무 복잡해서...', '{"generated_by": "seed script"}'::jsonb),
('8d0997fb', '지도가 잘못되어 있어서 엉뚱한 곳으로 갔습니다 너무 불편해요.', 1, '길찾기 (Wayfinding)', '센텀시티 (Centum City)', '지도가 잘못되어 있어서 엉뚱...', '{"generated_by": "seed script"}'::jsonb),
('9edd389f', '안내 표지판이 없어서 어디로 가야할지 모르겠어요.', 1, '길찾기 (Wayfinding)', '센텀시티 (Centum City)', '안내 표지판이 없어서 어디로...', '{"generated_by": "seed script"}'::jsonb),
('5b1d5e5f', '길 안내가 불친절합니다 너무 불편해요.', 1, '길찾기 (Wayfinding)', '센텀시티 (Centum City)', '길 안내가 불친절합니다 너무...', '{"generated_by": "seed script"}'::jsonb),
('f87d30ac', '쇼핑몰 내부가 미로 같아서 찾기가 힘들어요 진짜 불편해요.', 1, '길찾기 (Wayfinding)', '센텀시티 (Centum City)', '쇼핑몰 내부가 미로 같아서 ...', '{"generated_by": "seed script"}'::jsonb),
('d9008cd9', '안내 표지판이 없어서 어디로 가야할지 모르겠어요 진짜 불편해요.', 1, '길찾기 (Wayfinding)', '센텀시티 (Centum City)', '안내 표지판이 없어서 어디로...', '{"generated_by": "seed script"}'::jsonb),
('4fbc92bb', '안내 표지판이 없어서 어디로 가야할지 모르겠어요 진짜 불편해요.', 1, '길찾기 (Wayfinding)', '센텀시티 (Centum City)', '안내 표지판이 없어서 어디로...', '{"generated_by": "seed script"}'::jsonb),
('2ccc1ab8', '쇼핑몰 내부가 미로 같아서 찾기가 힘들어요 항상 불편해요.', 1, '길찾기 (Wayfinding)', '센텀시티 (Centum City)', '쇼핑몰 내부가 미로 같아서 ...', '{"generated_by": "seed script"}'::jsonb),
('e34c25bb', '지하철 출구가 너무 복잡해서 길을 잃었어요 진짜 불편해요.', 1, '길찾기 (Wayfinding)', '센텀시티 (Centum City)', '지하철 출구가 너무 복잡해서...', '{"generated_by": "seed script"}'::jsonb),
('8e9670ba', '쇼핑몰 내부가 미로 같아서 찾기가 힘들어요.', 1, '길찾기 (Wayfinding)', '센텀시티 (Centum City)', '쇼핑몰 내부가 미로 같아서 ...', '{"generated_by": "seed script"}'::jsonb),
('a2133d2a', '지하철 출구가 너무 복잡해서 길을 잃었어요 진짜 불편해요.', 1, '길찾기 (Wayfinding)', '센텀시티 (Centum City)', '지하철 출구가 너무 복잡해서...', '{"generated_by": "seed script"}'::jsonb),
('d977ab6f', '안내 표지판이 없어서 어디로 가야할지 모르겠어요 진짜 불편해요.', 1, '길찾기 (Wayfinding)', '센텀시티 (Centum City)', '안내 표지판이 없어서 어디로...', '{"generated_by": "seed script"}'::jsonb),
('d587b3c5', '쇼핑몰 내부가 미로 같아서 찾기가 힘들어요 정말 불편해요.', 1, '길찾기 (Wayfinding)', '센텀시티 (Centum City)', '쇼핑몰 내부가 미로 같아서 ...', '{"generated_by": "seed script"}'::jsonb),
('58f85369', '지도가 잘못되어 있어서 엉뚱한 곳으로 갔습니다.', 1, '길찾기 (Wayfinding)', '센텀시티 (Centum City)', '지도가 잘못되어 있어서 엉뚱...', '{"generated_by": "seed script"}'::jsonb),
('6ab3d932', '쇼핑몰 내부가 미로 같아서 찾기가 힘들어요 너무 불편해요.', 1, '길찾기 (Wayfinding)', '센텀시티 (Centum City)', '쇼핑몰 내부가 미로 같아서 ...', '{"generated_by": "seed script"}'::jsonb),
('4c252ca4', '안내 표지판이 없어서 어디로 가야할지 모르겠어요.', 1, '길찾기 (Wayfinding)', '센텀시티 (Centum City)', '안내 표지판이 없어서 어디로...', '{"generated_by": "seed script"}'::jsonb),
('c0fba284', '길 안내가 불친절합니다.', 1, '길찾기 (Wayfinding)', '센텀시티 (Centum City)', '길 안내가 불친절합니다....', '{"generated_by": "seed script"}'::jsonb),
('7dac659e', '지도가 잘못되어 있어서 엉뚱한 곳으로 갔습니다 매번 불편해요.', 1, '길찾기 (Wayfinding)', '센텀시티 (Centum City)', '지도가 잘못되어 있어서 엉뚱...', '{"generated_by": "seed script"}'::jsonb),
('293d69bd', '쇼핑몰 내부가 미로 같아서 찾기가 힘들어요 너무 불편해요.', 1, '길찾기 (Wayfinding)', '센텀시티 (Centum City)', '쇼핑몰 내부가 미로 같아서 ...', '{"generated_by": "seed script"}'::jsonb),
('4c7c20f1', '지도가 잘못되어 있어서 엉뚱한 곳으로 갔습니다.', 1, '길찾기 (Wayfinding)', '센텀시티 (Centum City)', '지도가 잘못되어 있어서 엉뚱...', '{"generated_by": "seed script"}'::jsonb),
('7f48b88c', '지도가 잘못되어 있어서 엉뚱한 곳으로 갔습니다 너무 불편해요.', 1, '길찾기 (Wayfinding)', '센텀시티 (Centum City)', '지도가 잘못되어 있어서 엉뚱...', '{"generated_by": "seed script"}'::jsonb),
('8af46295', '쇼핑몰 내부가 미로 같아서 찾기가 힘들어요 진짜 불편해요.', 1, '길찾기 (Wayfinding)', '센텀시티 (Centum City)', '쇼핑몰 내부가 미로 같아서 ...', '{"generated_by": "seed script"}'::jsonb),
('3da601cc', '길 안내가 불친절합니다.', 1, '길찾기 (Wayfinding)', '센텀시티 (Centum City)', '길 안내가 불친절합니다....', '{"generated_by": "seed script"}'::jsonb),
('63092079', '지하철 출구가 너무 복잡해서 길을 잃었어요 정말 불편해요.', 1, '길찾기 (Wayfinding)', '센텀시티 (Centum City)', '지하철 출구가 너무 복잡해서...', '{"generated_by": "seed script"}'::jsonb),
('e4d3021c', '지도가 잘못되어 있어서 엉뚱한 곳으로 갔습니다.', 1, '길찾기 (Wayfinding)', '센텀시티 (Centum City)', '지도가 잘못되어 있어서 엉뚱...', '{"generated_by": "seed script"}'::jsonb),
('dccbd316', '안내 표지판이 없어서 어디로 가야할지 모르겠어요 항상 불편해요.', 1, '길찾기 (Wayfinding)', '센텀시티 (Centum City)', '안내 표지판이 없어서 어디로...', '{"generated_by": "seed script"}'::jsonb),
('b56f2bf3', '쇼핑몰 내부가 미로 같아서 찾기가 힘들어요.', 1, '길찾기 (Wayfinding)', '센텀시티 (Centum City)', '쇼핑몰 내부가 미로 같아서 ...', '{"generated_by": "seed script"}'::jsonb),
('01958607', '안내 표지판이 없어서 어디로 가야할지 모르겠어요 진짜 불편해요.', 1, '길찾기 (Wayfinding)', '센텀시티 (Centum City)', '안내 표지판이 없어서 어디로...', '{"generated_by": "seed script"}'::jsonb),
('ecce5a92', '지하철 출구가 너무 복잡해서 길을 잃었어요.', 1, '길찾기 (Wayfinding)', '센텀시티 (Centum City)', '지하철 출구가 너무 복잡해서...', '{"generated_by": "seed script"}'::jsonb),
('ba452827', '길 안내가 불친절합니다 매번 불편해요.', 1, '길찾기 (Wayfinding)', '센텀시티 (Centum City)', '길 안내가 불친절합니다 매번...', '{"generated_by": "seed script"}'::jsonb),
('2cf4bd0f', '지도가 잘못되어 있어서 엉뚱한 곳으로 갔습니다 항상 불편해요.', 1, '길찾기 (Wayfinding)', '센텀시티 (Centum City)', '지도가 잘못되어 있어서 엉뚱...', '{"generated_by": "seed script"}'::jsonb),
('a9cef1e7', '쇼핑몰 내부가 미로 같아서 찾기가 힘들어요 항상 불편해요.', 1, '길찾기 (Wayfinding)', '센텀시티 (Centum City)', '쇼핑몰 내부가 미로 같아서 ...', '{"generated_by": "seed script"}'::jsonb),
('0d36d2ae', '길 안내가 불친절합니다.', 1, '길찾기 (Wayfinding)', '센텀시티 (Centum City)', '길 안내가 불친절합니다....', '{"generated_by": "seed script"}'::jsonb),
('e847b9cd', '쇼핑몰 내부가 미로 같아서 찾기가 힘들어요.', 1, '길찾기 (Wayfinding)', '센텀시티 (Centum City)', '쇼핑몰 내부가 미로 같아서 ...', '{"generated_by": "seed script"}'::jsonb),
('10bc0fb9', '쇼핑몰 내부가 미로 같아서 찾기가 힘들어요 항상 불편해요.', 1, '길찾기 (Wayfinding)', '센텀시티 (Centum City)', '쇼핑몰 내부가 미로 같아서 ...', '{"generated_by": "seed script"}'::jsonb),
('42092aa2', '지도가 잘못되어 있어서 엉뚱한 곳으로 갔습니다 정말 불편해요.', 1, '길찾기 (Wayfinding)', '센텀시티 (Centum City)', '지도가 잘못되어 있어서 엉뚱...', '{"generated_by": "seed script"}'::jsonb),
('3d80277b', '지하철 출구가 너무 복잡해서 길을 잃었어요 정말 불편해요.', 1, '길찾기 (Wayfinding)', '센텀시티 (Centum City)', '지하철 출구가 너무 복잡해서...', '{"generated_by": "seed script"}'::jsonb),
('6b7e9a09', '지하철 출구가 너무 복잡해서 길을 잃었어요 너무 불편해요.', 1, '길찾기 (Wayfinding)', '센텀시티 (Centum City)', '지하철 출구가 너무 복잡해서...', '{"generated_by": "seed script"}'::jsonb),
('820d9bda', '지도가 잘못되어 있어서 엉뚱한 곳으로 갔습니다 너무 불편해요.', 1, '길찾기 (Wayfinding)', '센텀시티 (Centum City)', '지도가 잘못되어 있어서 엉뚱...', '{"generated_by": "seed script"}'::jsonb),
('23eff951', '매우 혼잡하고 정신이 없습니다 매번 불편해요.', 2, '기타 (Other)', '남포동 (Nampo-dong)', '매우 혼잡하고 정신이 없습니...', '{"generated_by": "seed script"}'::jsonb),
('0902e4c5', '노점상이 인도를 차지해서 걸을 공간이 없어요 매번 불편해요.', 2, '기타 (Other)', '남포동 (Nampo-dong)', '노점상이 인도를 차지해서 걸...', '{"generated_by": "seed script"}'::jsonb),
('8d01f9f0', '매우 혼잡하고 정신이 없습니다 진짜 불편해요.', 2, '기타 (Other)', '남포동 (Nampo-dong)', '매우 혼잡하고 정신이 없습니...', '{"generated_by": "seed script"}'::jsonb),
('f22408a2', '사람이 너무 많아서 밀려 다녔어요 정말 불편해요.', 2, '기타 (Other)', '남포동 (Nampo-dong)', '사람이 너무 많아서 밀려 다...', '{"generated_by": "seed script"}'::jsonb),
('fe4b8354', '관광객이 너무 많아서 보행이 불가능해요 정말 불편해요.', 2, '기타 (Other)', '남포동 (Nampo-dong)', '관광객이 너무 많아서 보행이...', '{"generated_by": "seed script"}'::jsonb),
('56673576', '관광객이 너무 많아서 보행이 불가능해요 매번 불편해요.', 2, '기타 (Other)', '남포동 (Nampo-dong)', '관광객이 너무 많아서 보행이...', '{"generated_by": "seed script"}'::jsonb),
('bd16caf5', '관광객이 너무 많아서 보행이 불가능해요 항상 불편해요.', 2, '기타 (Other)', '남포동 (Nampo-dong)', '관광객이 너무 많아서 보행이...', '{"generated_by": "seed script"}'::jsonb),
('dc0d1ee9', '길이 너무 좁아서 다니기가 힘듭니다 너무 불편해요.', 2, '기타 (Other)', '남포동 (Nampo-dong)', '길이 너무 좁아서 다니기가 ...', '{"generated_by": "seed script"}'::jsonb),
('90f9a0ed', '길이 너무 좁아서 다니기가 힘듭니다 진짜 불편해요.', 2, '기타 (Other)', '남포동 (Nampo-dong)', '길이 너무 좁아서 다니기가 ...', '{"generated_by": "seed script"}'::jsonb),
('5200c175', '길이 너무 좁아서 다니기가 힘듭니다 항상 불편해요.', 2, '기타 (Other)', '남포동 (Nampo-dong)', '길이 너무 좁아서 다니기가 ...', '{"generated_by": "seed script"}'::jsonb),
('608be722', '매우 혼잡하고 정신이 없습니다.', 2, '기타 (Other)', '남포동 (Nampo-dong)', '매우 혼잡하고 정신이 없습니...', '{"generated_by": "seed script"}'::jsonb),
('03050511', '사람이 너무 많아서 밀려 다녔어요 항상 불편해요.', 2, '기타 (Other)', '남포동 (Nampo-dong)', '사람이 너무 많아서 밀려 다...', '{"generated_by": "seed script"}'::jsonb),
('00aea5d7', '길이 너무 좁아서 다니기가 힘듭니다 매번 불편해요.', 2, '기타 (Other)', '남포동 (Nampo-dong)', '길이 너무 좁아서 다니기가 ...', '{"generated_by": "seed script"}'::jsonb),
('15d72bf0', '관광객이 너무 많아서 보행이 불가능해요 항상 불편해요.', 2, '기타 (Other)', '남포동 (Nampo-dong)', '관광객이 너무 많아서 보행이...', '{"generated_by": "seed script"}'::jsonb),
('0eac3418', '관광객이 너무 많아서 보행이 불가능해요.', 2, '기타 (Other)', '남포동 (Nampo-dong)', '관광객이 너무 많아서 보행이...', '{"generated_by": "seed script"}'::jsonb),
('4a993cc6', '길이 너무 좁아서 다니기가 힘듭니다 매번 불편해요.', 2, '기타 (Other)', '남포동 (Nampo-dong)', '길이 너무 좁아서 다니기가 ...', '{"generated_by": "seed script"}'::jsonb),
('ee265d57', '노점상이 인도를 차지해서 걸을 공간이 없어요 진짜 불편해요.', 2, '기타 (Other)', '남포동 (Nampo-dong)', '노점상이 인도를 차지해서 걸...', '{"generated_by": "seed script"}'::jsonb),
('c3514a12', '노점상이 인도를 차지해서 걸을 공간이 없어요.', 2, '기타 (Other)', '남포동 (Nampo-dong)', '노점상이 인도를 차지해서 걸...', '{"generated_by": "seed script"}'::jsonb),
('6a9055aa', '노점상이 인도를 차지해서 걸을 공간이 없어요 매번 불편해요.', 2, '기타 (Other)', '남포동 (Nampo-dong)', '노점상이 인도를 차지해서 걸...', '{"generated_by": "seed script"}'::jsonb),
('d2bdb802', '노점상이 인도를 차지해서 걸을 공간이 없어요 너무 불편해요.', 2, '기타 (Other)', '남포동 (Nampo-dong)', '노점상이 인도를 차지해서 걸...', '{"generated_by": "seed script"}'::jsonb),
('d5f1ee9e', '매우 혼잡하고 정신이 없습니다 너무 불편해요.', 2, '기타 (Other)', '남포동 (Nampo-dong)', '매우 혼잡하고 정신이 없습니...', '{"generated_by": "seed script"}'::jsonb),
('1f828a19', '노점상이 인도를 차지해서 걸을 공간이 없어요 진짜 불편해요.', 2, '기타 (Other)', '남포동 (Nampo-dong)', '노점상이 인도를 차지해서 걸...', '{"generated_by": "seed script"}'::jsonb),
('b11b0c76', '관광객이 너무 많아서 보행이 불가능해요.', 2, '기타 (Other)', '남포동 (Nampo-dong)', '관광객이 너무 많아서 보행이...', '{"generated_by": "seed script"}'::jsonb),
('74011eca', '노점상이 인도를 차지해서 걸을 공간이 없어요.', 2, '기타 (Other)', '남포동 (Nampo-dong)', '노점상이 인도를 차지해서 걸...', '{"generated_by": "seed script"}'::jsonb),
('651849eb', '매우 혼잡하고 정신이 없습니다 진짜 불편해요.', 2, '기타 (Other)', '남포동 (Nampo-dong)', '매우 혼잡하고 정신이 없습니...', '{"generated_by": "seed script"}'::jsonb),
('40bf85f2', '매우 혼잡하고 정신이 없습니다 진짜 불편해요.', 2, '기타 (Other)', '남포동 (Nampo-dong)', '매우 혼잡하고 정신이 없습니...', '{"generated_by": "seed script"}'::jsonb),
('94fdb42d', '노점상이 인도를 차지해서 걸을 공간이 없어요 항상 불편해요.', 2, '기타 (Other)', '남포동 (Nampo-dong)', '노점상이 인도를 차지해서 걸...', '{"generated_by": "seed script"}'::jsonb),
('ad2136f7', '사람이 너무 많아서 밀려 다녔어요.', 2, '기타 (Other)', '남포동 (Nampo-dong)', '사람이 너무 많아서 밀려 다...', '{"generated_by": "seed script"}'::jsonb),
('238565ac', '매우 혼잡하고 정신이 없습니다 진짜 불편해요.', 2, '기타 (Other)', '남포동 (Nampo-dong)', '매우 혼잡하고 정신이 없습니...', '{"generated_by": "seed script"}'::jsonb),
('95f9b420', '사람이 너무 많아서 밀려 다녔어요 너무 불편해요.', 2, '기타 (Other)', '남포동 (Nampo-dong)', '사람이 너무 많아서 밀려 다...', '{"generated_by": "seed script"}'::jsonb),
('4d5dca13', '사람이 너무 많아서 밀려 다녔어요 매번 불편해요.', 2, '기타 (Other)', '남포동 (Nampo-dong)', '사람이 너무 많아서 밀려 다...', '{"generated_by": "seed script"}'::jsonb),
('f234a8f0', '관광객이 너무 많아서 보행이 불가능해요 정말 불편해요.', 2, '기타 (Other)', '남포동 (Nampo-dong)', '관광객이 너무 많아서 보행이...', '{"generated_by": "seed script"}'::jsonb),
('ed5baa40', '매우 혼잡하고 정신이 없습니다 항상 불편해요.', 2, '기타 (Other)', '남포동 (Nampo-dong)', '매우 혼잡하고 정신이 없습니...', '{"generated_by": "seed script"}'::jsonb),
('9eb78888', '노점상이 인도를 차지해서 걸을 공간이 없어요.', 2, '기타 (Other)', '남포동 (Nampo-dong)', '노점상이 인도를 차지해서 걸...', '{"generated_by": "seed script"}'::jsonb),
('17b0b3b2', '사람이 너무 많아서 밀려 다녔어요 진짜 불편해요.', 2, '기타 (Other)', '남포동 (Nampo-dong)', '사람이 너무 많아서 밀려 다...', '{"generated_by": "seed script"}'::jsonb),
('3a4d39ca', '노점상이 인도를 차지해서 걸을 공간이 없어요 너무 불편해요.', 2, '기타 (Other)', '남포동 (Nampo-dong)', '노점상이 인도를 차지해서 걸...', '{"generated_by": "seed script"}'::jsonb),
('411c97a1', '길이 너무 좁아서 다니기가 힘듭니다 매번 불편해요.', 2, '기타 (Other)', '남포동 (Nampo-dong)', '길이 너무 좁아서 다니기가 ...', '{"generated_by": "seed script"}'::jsonb),
('e1f64628', '관광객이 너무 많아서 보행이 불가능해요.', 2, '기타 (Other)', '남포동 (Nampo-dong)', '관광객이 너무 많아서 보행이...', '{"generated_by": "seed script"}'::jsonb),
('aab27653', '길이 너무 좁아서 다니기가 힘듭니다 너무 불편해요.', 2, '기타 (Other)', '남포동 (Nampo-dong)', '길이 너무 좁아서 다니기가 ...', '{"generated_by": "seed script"}'::jsonb),
('ab0600ed', '노점상이 인도를 차지해서 걸을 공간이 없어요 정말 불편해요.', 2, '기타 (Other)', '남포동 (Nampo-dong)', '노점상이 인도를 차지해서 걸...', '{"generated_by": "seed script"}'::jsonb),
('275aa964', '관광객이 너무 많아서 보행이 불가능해요 매번 불편해요.', 2, '기타 (Other)', '남포동 (Nampo-dong)', '관광객이 너무 많아서 보행이...', '{"generated_by": "seed script"}'::jsonb),
('7fb072bb', '노점상이 인도를 차지해서 걸을 공간이 없어요 너무 불편해요.', 2, '기타 (Other)', '남포동 (Nampo-dong)', '노점상이 인도를 차지해서 걸...', '{"generated_by": "seed script"}'::jsonb),
('ab83966b', '사람이 너무 많아서 밀려 다녔어요 정말 불편해요.', 2, '기타 (Other)', '남포동 (Nampo-dong)', '사람이 너무 많아서 밀려 다...', '{"generated_by": "seed script"}'::jsonb),
('ecfb704a', '매우 혼잡하고 정신이 없습니다 정말 불편해요.', 2, '기타 (Other)', '남포동 (Nampo-dong)', '매우 혼잡하고 정신이 없습니...', '{"generated_by": "seed script"}'::jsonb),
('d4061622', '노점상이 인도를 차지해서 걸을 공간이 없어요 매번 불편해요.', 2, '기타 (Other)', '남포동 (Nampo-dong)', '노점상이 인도를 차지해서 걸...', '{"generated_by": "seed script"}'::jsonb);